// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogPath() {
  return window['go']['app']['App']['GetLogPath']();
}

export function GetServiceStatus() {
  return window['go']['app']['App']['GetServiceStatus']();
}

export function InstallService() {
  return window['go']['app']['App']['InstallService']();
}

export function InstallSystemService() {
  return window['go']['app']['App']['InstallSystemService']();
}

export function ReadLog() {
  return window['go']['app']['App']['ReadLog']();
}

export function StartService() {
  return window['go']['app']['App']['StartService']();
}

export function StopService() {
  return window['go']['app']['App']['StopService']();
}

export function UninstallService() {
  return window['go']['app']['App']['UninstallService']();
}
