// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogPath():Promise<string>;

export function GetServiceStatus():Promise<string>;

export function InstallService():Promise<string>;

export function InstallSystemService():Promise<string>;

export function ReadLog():Promise<string>;

export function StartService():Promise<string>;

export function StopService():Promise<string>;

export function UninstallService():Promise<string>;
